fragment MobilePackage on MobilePackage {
  price
  bandwidth
  smsCount
  minutesCount
  changeFee
  exitFine
  networkMode
  abroadPackage {
    price
    bandwidth
    smsCount
    minutesCount
    changeFee
    exitFine
    networkMode
  }
}