export const BACKGROUND = '#FFFFFF'
export const DEFAULT_STATUSBAR = 'transparent'
export const BLACK = '#000000'
export const TRANSPARENT = 'transparent'
export const WHITE = '#FFFFFF'
export const GRAY = '#F4F5FC'
export const TEXT_RED = '#FF423F'
export const DARK_RED = '#FF423F'
export const LIGHT_RED = '#FF423F4D'
export const GREEN = '#27AE60'
export const LIGHT_GREEN = '#27AE601A'

export const ERROR = '#EB5757'
export const SUCCESS = '#27AE60'
export const WARNING = '#FFC107'

export const TEXT_INPUT_PLACEHOLDER_DARK_COLOR = '#5E626C'
export const TEXT_INPUT_PLACEHOLDER_LIGHT_COLOR = '#949BAC'
export const TEXT_INPUT_DARK_COLOR = '#FFFFFF'
export const TEXT_INPUT_LIGHT_COLOR = '#000033'
export const TEXT_INPUT_DARK_BG_COLOR = '#2C2B30'
export const TEXT_INPUT_LIGHT_BG_COLOR = '#FFFFFF'
export const TEXT_INPUT_LIGHT_BORDER_ACTIVE_COLOR = '#F15223'
export const TEXT_INPUT_LIGHT_BORDER_INACTIVE_COLOR = '#CECFCF'
export const TEXT_INPUT_DARK_BORDER_ACTIVE_COLOR = '#2C2B30'
export const TEXT_INPUT_DARK_BORDER_INACTIVE_COLOR = '#CECFCF'

export const TEXT_LABEL_LIGHT_COLOR = '#000033'
export const TEXT_LABEL_DARK_COLOR = '#FFFFFF'

export const LABEL_DARK_COLOR = '#5E626C'
export const LABEL_LIGHT_COLOR = '#000033'

export const DROPDOWN_TEXT_COLOR = '#5E626C'
export const DROPDOWN_BUTTON_BG_COLOR = 'transparent'
export const DROPDOWN_BORDER_COLOR = '#CECFCF'
export const DROPDOWN_ACTIVE_BORDER_COLOR = '#000033'

export const STEPPER_TEXT_COLOR = '#5E626C'

export const BUTTON_DEFAULT_COLOR = '#2F333C'
export const BUTTON_DISABLED_COLOR = '#E0E0E0'
export const BUTTON_GRADIENT_START = '#FF7852'
export const BUTTON_GRADIENT_END = '#FF423F'

export const DOT_ACTIVE = '#FFFFFF'
export const DOT_INACTIVE = '#C4C4C4'

export const STEP_ACTIVE_BG_COLOR = '#F15223'
export const STEP_INACTIVE_BG_COLOR = '#F4F5FC'
export const STEP_SHADOW_COLOR = '#F15223A1'

export const TAB_MENU_ACTIVE_COLOR = '#898B94'
export const TAB_ACTIVE_TINT_COLOR = 'grey'
export const TAB_INACTIVE_TINT_COLOR = 'red'
export const TAB_BG_COLOR = '#353339'

export const PROFILE_GREETINGS_COLOR = '#FFFFFFCC'

export const PAGE_TITLE_COLOR = '#000033'
export const TITLE_LIGHT_COLOR = '#5E626C'
export const TITLE_DARK_COLOR = '#FFFFFF'

export const PRIMARY_BG_COLOR = '#222126'
export const ROW_DARK_BG_COLOR = '#2C2B30'
export const SIGNUP_TEXTFIELD_BG_COLOR = '#2C2B30'

export const DASHBOARD_ICON_COLORS = ['#008037', '#EF404A', '#FF7852']
export const DASHBOARD_SHADOW_COLOR = '#031455'

export const HOME_SUBTITLE_COLOR = '#ffffffb3'

export const PROGRESS_ACTIVE_START_COLOR = '#FF4440'
export const PROGRESS_ACTIVE_END_COLOR = '#C86247'
export const PROGRESS_INACTIVE_START_COLOR = '#BEC7D7'
export const PROGRESS_INACTIVE_END_COLOR = '#5E5A5A'
export const PROGRESS_ACTIVE_TEXT_COLOR = '#FFFFFF'
export const PROGRESS_INACTIVE_TEXT_COLOR = '#FFFFFF50'
export const PROGRESS_INACTIVE_STROKE_COLOR = '#FFFFFF2B'

export const OTHER_INFORMATION_SUB_SOURCE_BG_COLOR = '#F8FAFC'
export const OTHER_INFORMATION_SUB_SOURCE_DROP_BORDER = '#CECFCF'
export const OTHER_INFORMATION_SUB_FOOTER_CANCEL_BORDER_COLOR = '#7A7A7D'

export const MODAL_BACKDROP_COLOR = '#00000080'

export const SUMMARY_BORDER = '#CECFCF'
export const SUMMARY_CONTENT = '#000033'
export const SUMMARY_HEADER = '#7A7A7D'

export const CATEGORY_CONTENT = '#EF404A'

export const TOTAL_DESCRIPTION = '#008037'

export const REDUCING_COST_FORWARD_COLOR = '#F15223'
export const REDUCING_CARD_BORDER = '#FF7350'

export const SOURCE_MODAL_BUTTON_BORDER = '#7A7A7D'

export const PRICING_CIRCLE_ICON_BG_COLOR = '#F15223'
